// src/context/mockData.js

export const mockIconCategories = [
  {
    id: 1,
    level: 1,
    tolevelup: 80,
    maxquizzesperday: 3,
    maxgamesperday: 3,
    quizzestolevelup: 12,
    gamestolevelup: 10,
    feathers_needed_to_claim: 500,
  },
  {
    id: 2,
    level: 2,
    tolevelup: 2100,
    maxquizzesperday: 5,
    maxgamesperday: 5,
    quizzestolevelup: 22,
    gamestolevelup: 18,
    feathers_needed_to_claim: 495,
  },
  {
    id: 3,
    level: 3,
    tolevelup: 3300,
    maxquizzesperday: 7,
    maxgamesperday: 7,
    quizzestolevelup: 33,
    gamestolevelup: 27,
    feathers_needed_to_claim: 490,
  },
  {
    id: 4,
    level: 4,
    tolevelup: 4500,
    maxquizzesperday: 9,
    maxgamesperday: 9,
    quizzestolevelup: 45,
    gamestolevelup: 38,
    feathers_needed_to_claim: 485,
  },
  {
    id: 5,
    level: 5,
    tolevelup: 18000,
    maxquizzesperday: 12,
    maxgamesperday: 12,
    quizzestolevelup: 70,
    gamestolevelup: 70,
    feathers_needed_to_claim: 480,
  },
];
